/**
 * 教材页内的小标题只收录逐页核验过的内容；键使用稳定的图片索引。
 * 未核验页面返回 undefined，避免把章节标题自动复制到整组页面。
 */
const VERIFIED_PAGE_TITLES: Readonly<Record<string, Readonly<Record<number, string>>>> = {
  "11": {
    4: "Welcome to Our World!",
  },
  "12": {
    3: "Welcome to Our World!",
  },
  "13": {
    6: "Greetings and Introductions",
  },
  "14": {
    2: "Language in Use",
  },
  "26": {
    12: "Having a good time",
    20: "Spending money",
    30: "We are what we eat",
    38: "All in the family",
    48: "No place like home",
    56: "Friends forever",
    66: "Smart life",
    74: "A question of sport",
    84: "Wild and wonderful",
    92: "Out and about",
    102: "Future bodies",
    110: "Travel the world",
  },
  "27": {
    7: "Having a good time",
    15: "Spending money",
    25: "We are what we eat",
    33: "All in the family",
    43: "No place like home",
    51: "Friends forever",
    61: "Smart life",
    69: "A question of sport",
    79: "Wild and wonderful",
    87: "Out and about",
    97: "Future bodies",
    105: "Travel the world",
  },
  "28": {
    12: "Incredible people",
    20: "A good education",
    30: "On the screen",
    38: "Online life",
    48: "Music to my ears",
    56: "No planet B",
    66: "The future is now",
    74: "Science and us",
    84: "Working week",
    92: "Mind and body",
    102: "Breaking news",
    110: "Rules and regulations",
  },
  "29": {
    7: "Incredible people",
    15: "A good education",
    25: "On the screen",
    33: "Online life",
    43: "Music to my ears",
    51: "No planet B",
    61: "The future is now",
    69: "Science and us",
    79: "Working week",
    87: "Mind and body",
    97: "Breaking news",
    105: "Rules and regulations",
  },
  "9": {
    4: "Map of the units",
    6: "Introduction",
    7: "A2 Key for Schools content and overview",
    8: "Hi, how are you?",
    9: "Listening Part 1: Numbers",
    10: "Grammar: Present simple",
    11: "Vocabulary: Family members / Reading Part 2",
    12: "Three English Teenagers / Grammar: Adverbs of frequency",
    13: "Speaking Part 1 / Writing Part 6",
    14: "We're going home",
    15: "Time / Grammar: Present continuous",
    16: "Vocabulary: Rooms",
    17: "Reading Part 1",
    18: "Grammar: have got / Vocabulary: Furniture",
    19: "Speaking Part 1 / Writing Part 7",
    20: "Vocabulary and grammar review 1",
    21: "Vocabulary and grammar review 2",
    22: "Dinner time",
    23: "Young chef / Vocabulary: School lunches",
    24: "Grammar: Countable and uncountable nouns",
    25: "Listening Part 2 / Grammar: How much/many; a few, a little, a lot of",
    26: "Vocabulary: Food phrases / Reading Part 5",
    27: "Speaking Part 2",
    28: "I'm shopping!",
    29: "Grammar: Present continuous and present simple",
    30: "Vocabulary: Adjectives",
    31: "Reading Part 4: Alek Wek",
    32: "Grammar: too and enough / Vocabulary: Shops",
    33: "Speaking Part 1 / Writing Part 7",
    34: "Vocabulary and grammar review 3",
    35: "Vocabulary and grammar review 4",
    36: "It's my favourite sport!",
    37: "Joanna Middleton – a young gymnast / Comparatives and superlatives",
    38: "do, play and go with sports",
    39: "Listening Part 4",
    40: "Prepositions of time: at, in, on / Nationalities",
    41: "Writing Part 6 / Speaking Part 2",
    42: "Have you got any homework?",
    43: "Listening Part 3 / have to",
    44: "Classroom objects",
    45: "Student life",
    46: "Object pronouns / Education verbs",
    47: "Reading Part 5 / Speaking Part 2",
    48: "Vocabulary and grammar review 5",
    49: "Vocabulary and grammar review 6",
    50: "Let's go to the museum",
    51: "Past simple",
    53: "Buildings / Listening Part 4",
    54: "Imperatives / Directions",
    55: "Speaking Part 2 / Writing Part 6",
    56: "Did you get my message?",
    57: "Listening Part 5 / Technology verbs",
    58: "Past continuous",
    59: "Three video makers / Music",
    60: "can/can't, could/couldn't",
    61: "Reading Part 5 / Speaking Part 1",
    62: "Vocabulary and grammar review 7",
    63: "Vocabulary and grammar review 8",
    64: "I love that film!",
    65: "Paddington Bear",
    66: "Verbs with -ing or to infinitive",
    67: "Suggesting, accepting and refusing / Listening Part 2",
    68: "The future / Adjectives",
    69: "Writing Part 7 / Speaking Part 2",
    70: "It's going to be sunny",
    71: "Vocabulary: What's the weather like?",
    72: "Grammar: be going to",
    73: "Reading Part 2: Holiday activities",
    74: "Vocabulary: Places / Grammar: must/mustn't",
    75: "Speaking Part 1 / Reading Part 5",
    76: "Vocabulary and grammar review 9",
    77: "Vocabulary and grammar review 10",
    78: "I like to keep fit",
    79: "Personal Trainer / Grammar: First conditional",
    80: "Vocabulary: Parts of the body",
    81: "Listening Part 4 / Grammar: something, anything, nothing, etc.",
    82: "Vocabulary: What's the matter?",
    83: "Speaking Part 2 / Writing Part 6",
    84: "Have you ever been on a plane?",
    85: "Reading Part 1 / Grammar: Present perfect",
    87: "Vocabulary: Vehicles / Listening Part 2",
    88: "Grammar: should/shouldn't / Vocabulary: Travel verbs",
    89: "Writing Part 7 / Speaking Part 1",
    90: "Vocabulary and grammar review 11",
    91: "Vocabulary and grammar review 12",
    92: "What's your hobby?",
    93: "Listening Part 3 / Grammar: Present perfect with for and since",
    94: "Vocabulary: Adverbs",
    95: "Reading Part 3: Teenage Go Player",
    96: "Grammar: may/might / Vocabulary: Jobs",
    97: "Writing Part 6 / Speaking Part 2",
    98: "Keep in touch!",
    99: "Grammar: The passive",
    100: "Vocabulary: Communication verbs / Reading Part 4",
    101: "Grammar: Present perfect with just, already and yet",
    102: "Vocabulary: -ed/-ing adjectives / Reading Part 5",
    103: "Speaking Parts 1 and 2",
    104: "Vocabulary and grammar review 13",
    105: "Vocabulary and grammar review 14",
    106: "Present simple",
    107: "Adverbs of frequency",
    108: "Present continuous",
    109: "Have got",
    110: "Countable and uncountable nouns",
    111: "How much/many; a few, a little, a lot of",
    112: "Present continuous and present simple / Too and enough",
    113: "Comparatives and superlatives",
    114: "Prepositions of time: at, in, on",
    115: "Have to / Object pronouns",
    116: "Past simple",
    117: "Imperatives",
    119: "Past continuous",
    120: "Can/can't, could/couldn't + infinitive without to",
    121: "-ing or to infinitive after verbs, adjectives and prepositions",
    122: "The future: will / Present continuous for the future / Present simple for the future",
    123: "Be going to",
    124: "Must/mustn't",
    125: "First conditional",
    126: "Something, anything, nothing, etc.",
    127: "Present perfect",
    128: "Should/shouldn't",
    129: "Present perfect with for and since / May/might",
    130: "The passive",
    131: "Present perfect with just, already and yet",
    132: "Phrasal verb builder: Getting about / In the morning",
    133: "People and communication / Other phrasal verbs",
    134: "Irregular verbs",
    135: "Writing bank: How to make your writing better: Adjectives",
    136: "How to make your writing better: Adverbs and interesting verbs",
    137: "Use verb forms correctly to talk about the past, present and future",
    138: "Use linking words and relative pronouns to make longer sentences",
    139: "Writing Part 6: A short message",
    141: "Writing Part 7: A story",
    143: "Speaking bank: Giving personal information / Talking about habits, likes and dislikes",
    144: "Giving opinions and reasons",
    145: "Agreeing and disagreeing / Dealing with problems",
    146: "Speaking Part 1",
    147: "Speaking Part 2",
    149: "Extra resources",
    151: "Answer key and audio scripts: 1 Hi, how are you?",
    153: "2 We're going home",
    154: "Vocabulary and grammar review 1 / Vocabulary and grammar review 2 / 3 Dinner time",
    156: "4 I'm shopping!",
    157: "Vocabulary and grammar review 3",
    158: "Vocabulary and grammar review 4 / 5 It's my favourite sport!",
    160: "6 Have you got any homework?",
    161: "Education verbs / Reviews 5–6 / Unit 7",
    162: "Unit 7",
    163: "Unit 7 / Unit 8",
    164: "Unit 8",
    165: "Reviews 7–8 / Unit 9",
    166: "Unit 9 / Unit 10",
    167: "Unit 10",
    168: "Unit 10 / Review 9",
    169: "Review 10 / Unit 11",
    170: "Unit 11",
    171: "Unit 12",
    172: "Unit 12 / Review 11",
    173: "Review 12 / Unit 13",
    174: "Unit 13",
    175: "Unit 14",
    176: "Unit 14 / Review 13",
    177: "Review 14 / Grammar reference",
    178: "Grammar reference",
    179: "Grammar reference",
    180: "Grammar reference",
    181: "Phrasal verb builder / Writing bank",
    182: "Writing bank: Linking words / Writing Parts 6–7",
    183: "Speaking bank: Personal information to dealing with problems",
    184: "Speaking Parts 1 and 2",
    186: "Acknowledgements",
  },
};

export const resolveBookPageTitle = (
  bookId: string,
  imageIndex: number,
): string | undefined => VERIFIED_PAGE_TITLES[bookId]?.[imageIndex];

/**
 * 教材目录节点可作为该节点起始页的可靠标题来源。
 * 页面卡片已有章节上下文，因此去掉重复的 `Unit N` 前缀；
 * 只有 Unit 编号而没有实际标题时不追加内容。
 */
export const resolveCatalogPageTitle = (catalogTitle: string): string | undefined => {
  const title = catalogTitle.trim();
  if (!title) return undefined;
  if (/^Unit\s+\d+$/i.test(title)) return undefined;

  const unitMatch = title.match(
    /^Unit\s+\d+(?:\s*[:：.\-–—]\s*|\s+)(.+)$/i,
  );
  return unitMatch?.[1].trim() || title;
};
